### ISSUE TITLE
SyntaxError: The requested module '/polyfill/node/path.ts' does not provide an export named 'default'

### ISSUE THREAD

**Issue by timonson** [lucacasonato/dext.ts#48] opened 2020-10-15 16:29 UTC
While trying to install `dext` with the latest deno version by running `deno install -r --allow-read --allow-write --allow-env --allow-net --allow-run --unstable -f -n dext https://deno.land/x/dext@0.9.0/cli.ts`, I get the following errors:

```bash
Warning Failed to get compiled source code of "https://cdn.dreg.dev/polyfill/node/path.ts".
Reason: No such file or directory (os error 2)
If the source file provides only type exports, prefer to use "import type" or "export type" syntax instead.
Warning Failed to get compiled source code of "https://cdn.dreg.dev/polyfill/node/process.ts".
Reason: No such file or directory (os error 2)
If the source file provides only type exports, prefer to use "import type" or "export type" syntax instead.
error: Uncaught SyntaxError: The requested module '/polyfill/node/path.ts' does not provide an export named 'default'
```

**Comment by lucacasonato** [comment] 2020-10-15 16:40
Duplicate of #39. Try with `--no-check`:
```
deno install --allow-read --allow-write --allow-env --allow-net --allow-run --unstable --no-check -f -n dext https://deno.land/x/dext@0.9.1/cli.ts
```

**Closed by lucacasonato** 2020-10-15 16:40 UTC
